// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_5wbeI45Zmk2AAwkeVtq-xzzWXUir8t8',
    appId: '1:793447370545:web:4f5dbd7dc060f5f52bea10',
    messagingSenderId: '793447370545',
    projectId: 'wilobu-d21b2',
    authDomain: 'wilobu-d21b2.firebaseapp.com',
    storageBucket: 'wilobu-d21b2.firebasestorage.app',
    measurementId: 'G-EX8YYCMB1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwb4mSvw5ufwFk27woLN15JIHcWdcJ8Do',
    appId: '1:793447370545:android:5ad1367f57ce05912bea10',
    messagingSenderId: '793447370545',
    projectId: 'wilobu-d21b2',
    storageBucket: 'wilobu-d21b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYfgDnXhpMRqK3sHmHLQmHQYtmVgNE4-4',
    appId: '1:793447370545:ios:2f7dd281c25b229a2bea10',
    messagingSenderId: '793447370545',
    projectId: 'wilobu-d21b2',
    storageBucket: 'wilobu-d21b2.firebasestorage.app',
    iosBundleId: 'com.example.wilobuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYfgDnXhpMRqK3sHmHLQmHQYtmVgNE4-4',
    appId: '1:793447370545:ios:2f7dd281c25b229a2bea10',
    messagingSenderId: '793447370545',
    projectId: 'wilobu-d21b2',
    storageBucket: 'wilobu-d21b2.firebasestorage.app',
    iosBundleId: 'com.example.wilobuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_5wbeI45Zmk2AAwkeVtq-xzzWXUir8t8',
    appId: '1:793447370545:web:132da5bf5712511f2bea10',
    messagingSenderId: '793447370545',
    projectId: 'wilobu-d21b2',
    authDomain: 'wilobu-d21b2.firebaseapp.com',
    storageBucket: 'wilobu-d21b2.firebasestorage.app',
    measurementId: 'G-DQC4ESYN66',
  );
}
